# Generated by Django 6.1 on 2026-08-29 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TicketAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('movie_name', models.CharField(max_length=255)),
                ('bms_url', models.URLField(help_text='Direct BMS buy tickets link', max_length=500)),
                ('theatre_filter', models.CharField(blank=True, help_text="Optional theatre filter (e.g. 'PVR', 'Srinivasa','Maruthi Theatre','Srinivasa Cine Complex','Geetha Annapurna Theatre','AVG Screens, 4K Dolby Atmos: Bhimavaram','Sri Padmalaya Cine Complex A/C 2K: Bhimavaram','Sri Vijayalakshmi Cine Complex: Bhimavaram')", max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('alert_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
