# Generated by Django 6.1 on 2026-09-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketalert',
            name='target_date',
            field=models.DateField(blank=True, help_text='Target show date (e.g. 2026-09-12)', null=True),
        ),
    ]
